### PR TITLE
Specify MSRV instead of fixing the toolchain

### PR DESCRIPTION
**Pull request by Nashtare**
# Description

Specifying a rust-toolchain file fixes the Rust version being used, while we should rather specify an MSRV instead, as is the rust-version field of Cargo.toml intended to be.

## PR Checklist:

- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added or updated tests that comprehensively prove my change is effective or that my feature works

### CODE REVIEW

**Comment by Nashtare** [comment]
I'm not sure why the CI for code-coverage is failing, it shouldn't. The error is the following:
```
Run cargo tarpaulin --verbose --engine llvm --release --out Xml
error: invalid value 'Xml' for '--out [<FMT>...]'
```

I've noticed it failing on other repos as well (for instance https://github.com/toposware/cheetah), though not really blocking.

**Comment by sebastiendan** [comment]
Swapping my review with Simon's as I think he can be of much greater value here

**Comment by Nashtare** [comment]
@sebastiendan Sure thing! Although the CI check being red is a bit ugly. As we'll publish this on crates.io at some point, we'll probably want to address it soon. But non-blocking for this particular PR.

**Comment by dvdplm** [comment]
> Run cargo tarpaulin --verbose --engine llvm --release --out Xml

Speculation: perhaps it should be `--out xml`? And it works for macos users because the FS is case insensitive?

**Comment by Nashtare** [comment]
> Speculation: perhaps it should be --out xml? And it works for macos users because the FS is case insensitive?

Perhaps, though I'm confused why it was working in the first place then.

Regarding the MSRV comment, I don't really have an objection to not setting a MSRV and just relying on the latest stable, it just felt more proper to have it declared (and I think as a general rule if every crate was specifying their MSRV this would definitely help the ecosystem) but I'll leave the experts decide here 🙂 
@Freyskeyd Do you have any opinion?

**Comment by Nashtare** [comment]
Closing in favor of https://github.com/topos-protocol/ice-frost/pull/9.

**Pull request closed without merging**
